# Generated by Django 5.2.15 on 2026-06-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_arrived_at_booking_provider_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
