# Generated by Django 6.0.6 on 2026-06-05 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_nepali', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(default='🔧', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(default='', max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('hourly_rate', models.IntegerField(blank=True, null=True)),
                ('service_area', models.CharField(default='', max_length=200)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('portfolio_photos', models.JSONField(blank=True, default=list)),
                ('id_document_url', models.URLField(blank=True, null=True)),
                ('id_document_type', models.CharField(blank=True, choices=[('CITIZENSHIP_CARD', 'Citizenship Card'), ('NATIONAL_ID', 'National ID'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('PASSPORT', 'Passport')], max_length=50, null=True)),
                ('selfie_url', models.URLField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE_NOW', 'Available Now'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('karma_points', models.IntegerField(default=0)),
                ('karma_level', models.CharField(choices=[('NONE', 'None'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='NONE', max_length=20)),
                ('average_rating', models.FloatField(default=0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('commission_rate', models.FloatField(default=0.1)),
                ('profile_completion', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='services.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
