# Generated by Django 5.2.15 on 2026-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_nepali',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
