# Generated by Django 6.0.6 on 2026-06-05 11:41

import ftl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftlalert',
            name='contact_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ftlalert',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftlalert',
            name='contact_method',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('IN_APP', 'In App')], default='PHONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ftlalert',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=ftl.models.default_expiry, null=True),
        ),
        migrations.AlterField(
            model_name='ftlalert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('REMOVED', 'Removed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='ftlalert',
            name='type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('PET', 'Pet'), ('ITEM', 'Item'), ('VEHICLE', 'Vehicle')], max_length=20),
        ),
    ]
