# Generated by Django 5.2.15 on 2026-06-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftl', '0002_ftlalert_contact_value_ftlalert_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftlalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ftl/'),
        ),
    ]
