# Generated by Django 6.0.6 on 2026-06-05 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FTLAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LOST_ITEM', 'Lost Item'), ('LOST_PET', 'Lost Pet'), ('MISSING_PERSON', 'Missing Person')], max_length=20)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('last_seen_location', models.CharField(default='', max_length=255)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('qr_code', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_method', models.CharField(choices=[('ANONYMOUS_APP', 'Anonymous App'), ('SHOW_PHONE', 'Show Phone'), ('SHOW_EMAIL', 'Show Email')], default='ANONYMOUS_APP', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('EXPIRED', 'Expired'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftl_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
