# Generated by Django 6.0.6 on 2026-06-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
