# Generated by Django 5.2.15 on 2026-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_customer_lat_booking_customer_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
