# Generated by Django 5.2.15 on 2026-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_notification_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
